[settings]
lockfile = true
task.run_auto_install = false

[tools]
node = "24.21.0"
pnpm = "12.3.4"
hk = "1.58.1"
pkl = "0.32.1"
typos = "1.50.1"
betterleaks = "v1.8.1"
actionlint = "1.7.12"
pinact = "4.1.1"

[env]
_.path = ["{{config_root}}/node_modules/.bin"]
