name: Publish to npm

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  actions:
    name: Actions
    uses: ./.github/workflows/actions.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    name: Publish to npm
    needs: actions
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    environment:
      name: npm
      url: https://www.npmjs.com/package/satteri-kern

    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          install_args: node pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish package
        run: npm publish --provenance --access public
