name: Test

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  vitest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run cov

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          fail_ci_if_error: true
          files: ./junit.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
